runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /qrcode.png
  static_files: qrcode.png
  upload: qrcode.png

- url: /api
  script: main.app

- url: /controll.js
  static_files: controll.js
  upload: controll.js
